version: '3.8'

services:
  backend-avaliacao:
    build: .
    ports:
      - "3101:3101"
    env_file:
      - .env
    volumes:
      - ./combined.log:/app/combined.log
      - ./error.log:/app/error.log
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
